# Generated by Django 5.2.10 on 2026-01-13 16:05

from django.db import migrations, models, connection


def add_index_if_not_exists(apps, schema_editor):
    """Add index only if it doesn't already exist."""
    with connection.cursor() as cursor:
        # Check if index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'chunk_embed_embeddi_88d9e0_idx'
            );
        """)
        index_exists = cursor.fetchone()[0]
        
        if not index_exists:
            # Create the index on the correct table name
            cursor.execute("""
                CREATE INDEX chunk_embed_embeddi_88d9e0_idx 
                ON chunk_embeddings (embedding_model);
            """)


def remove_index_if_exists(apps, schema_editor):
    """Remove index if it exists."""
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS chunk_embed_embeddi_88d9e0_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_fix_index_names'),
    ]

    operations = [
        migrations.RunPython(
            add_index_if_not_exists,
            reverse_code=remove_index_if_exists,
        ),
    ]
